//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Confirmacion.WS_Confirmacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ateb.timbrado.com.mx/CFDI/Confirmacion/", ConfigurationName="WS_Confirmacion.CFDICodigoConfirmacionSoap")]
    public interface CFDICodigoConfirmacionSoap {
        
        // CODEGEN: Generating message contract since message ConfirmarRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ateb.timbrado.com.mx/CFDI/Confirmacion/Confirmar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WA_Confirmacion.WS_Confirmacion.ConfirmarResponse Confirmar(WA_Confirmacion.WS_Confirmacion.ConfirmarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ateb.timbrado.com.mx/CFDI/Confirmacion/Confirmar", ReplyAction="*")]
        System.Threading.Tasks.Task<WA_Confirmacion.WS_Confirmacion.ConfirmarResponse> ConfirmarAsync(WA_Confirmacion.WS_Confirmacion.ConfirmarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ateb.timbrado.com.mx/CFDI/Confirmacion/")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaHoraPeticionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaHoraPeticion {
            get {
                return this.fechaHoraPeticionField;
            }
            set {
                this.fechaHoraPeticionField = value;
                this.RaisePropertyChanged("FechaHoraPeticion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ateb.timbrado.com.mx/CFDI/Confirmacion/")]
    public partial class ConfirmResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mensageField;
        
        private string[] codesField;
        
        private string estatusField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mensage {
            get {
                return this.mensageField;
            }
            set {
                this.mensageField = value;
                this.RaisePropertyChanged("Mensage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Codes {
            get {
                return this.codesField;
            }
            set {
                this.codesField = value;
                this.RaisePropertyChanged("Codes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("Estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Confirmar", WrapperNamespace="http://ateb.timbrado.com.mx/CFDI/Confirmacion/", IsWrapped=true)]
    public partial class ConfirmarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ateb.timbrado.com.mx/CFDI/Confirmacion/")]
        public WA_Confirmacion.WS_Confirmacion.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ateb.timbrado.com.mx/CFDI/Confirmacion/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] XmlBytes;
        
        public ConfirmarRequest() {
        }
        
        public ConfirmarRequest(WA_Confirmacion.WS_Confirmacion.AuthenticationHeader AuthenticationHeader, byte[] XmlBytes) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.XmlBytes = XmlBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarResponse", WrapperNamespace="http://ateb.timbrado.com.mx/CFDI/Confirmacion/", IsWrapped=true)]
    public partial class ConfirmarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ateb.timbrado.com.mx/CFDI/Confirmacion/", Order=0)]
        public WA_Confirmacion.WS_Confirmacion.ConfirmResult ConfirmarResult;
        
        public ConfirmarResponse() {
        }
        
        public ConfirmarResponse(WA_Confirmacion.WS_Confirmacion.ConfirmResult ConfirmarResult) {
            this.ConfirmarResult = ConfirmarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CFDICodigoConfirmacionSoapChannel : WA_Confirmacion.WS_Confirmacion.CFDICodigoConfirmacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFDICodigoConfirmacionSoapClient : System.ServiceModel.ClientBase<WA_Confirmacion.WS_Confirmacion.CFDICodigoConfirmacionSoap>, WA_Confirmacion.WS_Confirmacion.CFDICodigoConfirmacionSoap {
        
        public CFDICodigoConfirmacionSoapClient() {
        }
        
        public CFDICodigoConfirmacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFDICodigoConfirmacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFDICodigoConfirmacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFDICodigoConfirmacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Confirmacion.WS_Confirmacion.ConfirmarResponse WA_Confirmacion.WS_Confirmacion.CFDICodigoConfirmacionSoap.Confirmar(WA_Confirmacion.WS_Confirmacion.ConfirmarRequest request) {
            return base.Channel.Confirmar(request);
        }
        
        public WA_Confirmacion.WS_Confirmacion.ConfirmResult Confirmar(WA_Confirmacion.WS_Confirmacion.AuthenticationHeader AuthenticationHeader, byte[] XmlBytes) {
            WA_Confirmacion.WS_Confirmacion.ConfirmarRequest inValue = new WA_Confirmacion.WS_Confirmacion.ConfirmarRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.XmlBytes = XmlBytes;
            WA_Confirmacion.WS_Confirmacion.ConfirmarResponse retVal = ((WA_Confirmacion.WS_Confirmacion.CFDICodigoConfirmacionSoap)(this)).Confirmar(inValue);
            return retVal.ConfirmarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Confirmacion.WS_Confirmacion.ConfirmarResponse> WA_Confirmacion.WS_Confirmacion.CFDICodigoConfirmacionSoap.ConfirmarAsync(WA_Confirmacion.WS_Confirmacion.ConfirmarRequest request) {
            return base.Channel.ConfirmarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Confirmacion.WS_Confirmacion.ConfirmarResponse> ConfirmarAsync(WA_Confirmacion.WS_Confirmacion.AuthenticationHeader AuthenticationHeader, byte[] XmlBytes) {
            WA_Confirmacion.WS_Confirmacion.ConfirmarRequest inValue = new WA_Confirmacion.WS_Confirmacion.ConfirmarRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.XmlBytes = XmlBytes;
            return ((WA_Confirmacion.WS_Confirmacion.CFDICodigoConfirmacionSoap)(this)).ConfirmarAsync(inValue);
        }
    }
}
